# Generated by Django 5.0.6 on 2024-05-26 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='failed_login',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
