version: '3'

services:
  app:
    build: .
    volumes:
      - .:/Gestion_Tickets
    ports:
      - 8000:8000
    image: app:Gestion_Tickets
    container_name: Gestion_Tickets_container
    command: python manage.py runserver 0.0.0.0:8000