# Generated by Django 5.0.4 on 2024-05-22 16:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Admin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Personnel',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('date', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('Admin.user',),
        ),
        migrations.CreateModel(
            name='TicketConsommer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_ticket', models.CharField(choices=[('pdej', 'Petit-déjeuner'), ('dej', 'Déjeuner'), ('dinner', 'Dîner')], max_length=10)),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('date', models.DateField(auto_now_add=True)),
                ('personnel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='Personnels.personnel')),
            ],
        ),
    ]
