# Generated by Django 3.2.6 on 2024-04-05 21:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Personnels', '0002_auto_20240402_1019'),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketConsommer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_ticket', models.CharField(choices=[('pdej', 'Petit-déjeuner'), ('dej', 'Déjeuner'), ('dinner', 'Dîner')], max_length=10)),
                ('date', models.DateField(auto_now_add=True)),
                ('personnel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='Personnels.personnel')),
            ],
        ),
    ]
