# Generated by Django 3.2.6 on 2024-04-05 21:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Personnels', '0003_ticketconsommer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personnel',
            name='nbre_tickets_dej_consommer',
        ),
        migrations.RemoveField(
            model_name='personnel',
            name='nbre_tickets_dinner_consommer',
        ),
        migrations.RemoveField(
            model_name='personnel',
            name='nbre_tickets_pdej_consommer',
        ),
    ]
