# Generated by Django 3.2.6 on 2024-04-05 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Personnels', '0004_auto_20240405_2135'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketconsommer',
            name='quantity',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
