# Generated by Django 3.2.6 on 2024-03-14 07:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Etudiants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket_Repas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nbre_tickets_repas', models.FloatField(blank=True, default=0.0, max_length=65, null=True)),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets_repas', to='Etudiants.etudiant')),
            ],
        ),
        migrations.CreateModel(
            name='Ticket_Dej',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nbre_tickets_dej', models.FloatField(blank=True, default=0.0, max_length=65, null=True)),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets_dej', to='Etudiants.etudiant')),
            ],
        ),
    ]
