# Generated by Django 3.2.6 on 2024-03-24 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tickets', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket_dej',
            name='nbre_tickets_dej',
        ),
        migrations.AddField(
            model_name='ticket_dej',
            name='nbre_tickets_repas',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='ticket_repas',
            name='nbre_tickets_repas',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
    ]
