# Generated by Django 3.2.6 on 2024-04-07 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tickets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket_dej',
            name='nbre_tickets_dej',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ticket_repas',
            name='nbre_tickets_repas',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
