# Generated by Django 3.2.6 on 2024-03-24 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tickets', '0002_auto_20240324_1345'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket_dej',
            old_name='nbre_tickets_repas',
            new_name='nbre_tickets_dej',
        ),
    ]
