# Generated by Django 3.2.6 on 2024-03-14 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Etudiants', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='etudiant',
            name='montant',
        ),
    ]
