# Generated by Django 3.2.6 on 2024-04-07 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Etudiants', '0002_alter_transaction_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='tickets_dej',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='tickets_pdej',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
